// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWtSmN-Zrd13PvGgZaCGrf1cOr7ing42s',
    appId: '1:600446626433:web:a4c4d2f986ee8e3d7cbb80',
    messagingSenderId: '600446626433',
    projectId: 'enchant-attire-575de',
    authDomain: 'enchant-attire-575de.firebaseapp.com',
    storageBucket: 'enchant-attire-575de.appspot.com',
    measurementId: 'G-S98JQ9YESE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5UCpz82U-ksm-afFxMP_P-FuFpZRLJzI',
    appId: '1:600446626433:android:2a49f3857be23c8a7cbb80',
    messagingSenderId: '600446626433',
    projectId: 'enchant-attire-575de',
    storageBucket: 'enchant-attire-575de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8Gd_vVXCDBk-20c6JLzsS7zdCFmAYx7c',
    appId: '1:600446626433:ios:741471abddb638a17cbb80',
    messagingSenderId: '600446626433',
    projectId: 'enchant-attire-575de',
    storageBucket: 'enchant-attire-575de.appspot.com',
    androidClientId: '600446626433-875t9gg7a3p3cd4o20e702spqdc34atb.apps.googleusercontent.com',
    iosClientId: '600446626433-lfde80g9f2ht6kuta8il32qnhbp4t639.apps.googleusercontent.com',
    iosBundleId: 'com.example.enchantAttireAdmin',
  );
}
